### ISSUE TITLE
Any news???

### ISSUE THREAD

**Issue by Drakaroft** [AdrienNeveu/FPSDesigner#1]
No updates for a year, any news? I need some help compiling with vs2017 :(

**Comment by DavidPeicho** [comment]
Actually, the software was created as a first year project, and is, consequently, not supported anymore.
If you really want to compile it, you will have to try an older version of VS (the 2012 should do the job).

**Comment by Drakaroft** [comment]
Ah right, thanks! 
(PS there is a link for an already compiled version?)

**Comment by AdrienNeveu** [comment]
There's no binaries yet, I'll try to compile it and upload it to GitHub today.
By the way, the website is up and running if you want to check it out: https://www.fpsdesigner.com

**Comment by Drakaroft** [comment]
Thanks! i checked the site and i really want to try it! Also i see that it use metro form that i really like. (VS2012 express is good for compile it? And there is really no way to compile in vs2017 the project seems amazing)
